name: planetas_astros_firebase 
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  flutter_colorpicker: ^1.0.0 
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: Pixelate 
      fonts:
        - asset: assets/fonts/Pixelate.ttf 
        
  assets:
    - assets/imgs/